const REPOS_ACTION_TYPES = {
  GET_REPOS: 'GET_REPOS',
  GET_REPOS_SUCCESS: 'GET_REPOS_SUCCESS',
  GET_REPOS_ERROR: 'GET_REPOS_ERROR',

  GET_SINGLE_REPO: 'GET_SINGLE_REPO',
  GET_SINGLE_REPO_SUCCESS: 'GET_SINGLE_REPO_SUCCESS',
  GET_SINGLE_REPO_ERROR: 'GET_SINGLE_REPO_ERROR',

  SET_SEARCH: 'SET_SEARCH',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_PAGES: 'SET_TOTAL_PAGES',
};

export default REPOS_ACTION_TYPES;
